# Services unlikely to appear in hospital/gov deployments
quake
minecraft
teamspeak
ventrilo
murmur
freelancer
icy
AndroMouse
gopher
uucp
nntp
gnutella
ident
sieve
cvspserver
whois
warcraft
kazaa-http
kazaa-peerpoint
napster
