amqp
apachemq
bittorrent
bittorrent-dht
bittorrent-tracker
bittorrent-udp-tracker
bittorrent-utp
ca-mq
dcerpc
dhcp
dns
docker
docker-swarm
domain
elasticsearch
ftp
ftp-data
http
http2
http-proxy
ibm-mqseries
ike
imap
java-message-service
java-object
jboss-remoting
kerberos-sec
krb5
microsoft-ds
mqtt
msrpc
ms-sql-m
ms-sql-s
ms-wbt-server
mysql
netbios-ssn
nfs
ntp
pgsql
postgresql
psql
psql-btrieve
qmqp
quic
rdp
rfb
sip
smb
smtp
snmp
sonicmq
ssh
ssl
stomp
telnet
tftp
tls
utorrent-udp
zmtp
